<html>
<head>
<title>Rotomasters | Specifications &amp; Diagrams</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
.headers {
	color: #585858;
	font-family: Verdana, Geneva, sans-serif;
	font-size: 36px;
	font-weight: bold;
}
.content {
	font-family: Verdana, Geneva, sans-serif;
	font-size: 12px;
	color: #585858;
}
.xl654065 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl664065 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6514346 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6614346 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6714346 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6814346 {padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:"\0022$\0022\#\,\#\#0\.00";
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
</style>
</head>
<?php include("header.php"); ?>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (dimensions.psd) -->
<table width="977" height="1778" border="0" align="center" cellpadding="0" cellspacing="0" id="Table_01">
	<tr>
		<td colspan="5" align="center">
			<img src="images/specs&diagrams_01.jpg" width="977" height="208" alt=""></td>
  </tr>
	<tr>
		<td colspan="5">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="5"><table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
		  <tr>
		    <td height="32" class="headers">Motor Dimensions</td>
	      </tr>
	    </table></td>
	</tr>
	<tr>
		<td rowspan="2">&nbsp;</td>
		<td colspan="3">
			<img src="images/specs&diagrams_05.png" width="775" height="391" alt=""></td>
		<td rowspan="2">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="3">
			<img src="images/specs&diagrams_07.png" width="775" height="1" alt=""></td>
	</tr>
	<tr>
		<td colspan="5"><!--[if !excel]>&nbsp;&nbsp;<![endif]-->
          <!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
          <!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
          <!----------------------------->
          <!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
          <!----------------------------->
          <div id="rotomasters-dimensions_4065" align=center x:publishsource="Excel">
            <table border=0 cellpadding=0 cellspacing=0 width=818 style='border-collapse:
 collapse;table-layout:fixed;width:612pt'>
              <col width=83 style='mso-width-source:userset;mso-width-alt:2958;width:62pt'>
              <col width=51 style='mso-width-source:userset;mso-width-alt:1820;width:38pt'>
              <col width=54 span=2 style='mso-width-source:userset;mso-width-alt:1905;
 width:40pt'>
              <col width=64 span=9 style='width:48pt'>
              <tr class=xl654065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 width=83 style='height:14.4pt;width:62pt;
  font-size:11.0pt;color:white;font-weight:700;text-decoration:none;text-underline-style:
  none;text-line-through:none;font-family:Calibri;border-top:1.0pt solid black;
  border-right:none;border-bottom:1.0pt solid black;border-left:none;
  background:#4F81BD;mso-pattern:#4F81BD none'>Frame Size</td>
                <td class=xl654065 width=51 style='width:38pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>A</td>
                <td class=xl654065 width=54 style='width:40pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>B</td>
                <td class=xl654065 width=54 style='width:40pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>C</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>D</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>E</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>F</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>NW</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>O</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>P</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>T</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>AB</td>
                <td class=xl654065 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>BA</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>7.5 HP</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>10.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>7.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>18.89</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>2.75</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>3.375</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>10.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>10.4</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>1.75</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>8.63</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>3.5</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt'>10 HP</td>
                <td class=xl664065>10.5</td>
                <td class=xl664065>9</td>
                <td class=xl664065>20.488</td>
                <td class=xl664065>5.25</td>
                <td class=xl664065>4.25</td>
                <td class=xl664065>3.5</td>
                <td class=xl664065>3.375</td>
                <td class=xl664065>10.5</td>
                <td class=xl664065>10.4</td>
                <td class=xl664065>1.75</td>
                <td class=xl664065>8.63</td>
                <td class=xl664065>3.5</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>15 HP</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>10.8</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>23.292</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>6.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.125</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12.79</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12.6</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>2.15</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>11.2</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.25</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt'>20 HP</td>
                <td class=xl664065>12.5</td>
                <td class=xl664065>12.5</td>
                <td class=xl664065>25.058</td>
                <td class=xl664065>6.25</td>
                <td class=xl664065>5</td>
                <td class=xl664065>5</td>
                <td class=xl664065>4</td>
                <td class=xl664065>12.79</td>
                <td class=xl664065>12.6</td>
                <td class=xl664065>2.15</td>
                <td class=xl664065>11.2</td>
                <td class=xl664065>4.25</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>25 HP</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>14</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>26.63</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>7</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5.5</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.75</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.625</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>13.98</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>13.98</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>2.35</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>4.75</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt'>30 HP</td>
                <td class=xl664065>14</td>
                <td class=xl664065>14</td>
                <td class=xl664065>28.182</td>
                <td class=xl664065>7</td>
                <td class=xl664065>5.5</td>
                <td class=xl664065>5.5</td>
                <td class=xl664065>4.625</td>
                <td class=xl664065>13.98</td>
                <td class=xl664065>13.98</td>
                <td class=xl664065>2.35</td>
                <td class=xl664065>12</td>
                <td class=xl664065>4.75</td>
              </tr>
              <tr class=xl664065 height=19 style='height:14.4pt'>
                <td height=19 class=xl654065 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;border-top:none;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#D9D9D9;
  mso-pattern:#D9D9D9 none'>40 HP</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>16</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>14</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>29.95</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>8</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>6.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5.25</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>15.55</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>15.55</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>2.55</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>13.4</td>
                <td class=xl664065 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none;background:#D9D9D9;mso-pattern:#D9D9D9 none'>5.25</td>
              </tr>
              <![if supportMisalignedColumns]>
              <tr height=0 style='display:none'>
                <td width=83 style='width:62pt'></td>
                <td width=51 style='width:38pt'></td>
                <td width=54 style='width:40pt'></td>
                <td width=54 style='width:40pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
              </tr>
              <![endif]>
            </table>
          </div>
          <!----------------------------->
          <!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
        <!-----------------------------></td>
	</tr>
	<tr valign="middle">
		<td colspan="5"><!--[if !excel]>&nbsp;&nbsp;<![endif]-->
          <p>
            <!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
            <!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
            <!----------------------------->
            <!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
            <!----------------------------->
          </p>
          <table width="900" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              <td>&nbsp;</td>
            </tr>
          </table>
          <div id="rotomasters-dimensions_14346" align=center x:publishsource="Excel">
            <table border=0 cellpadding=0 cellspacing=0 width=749 style='border-collapse:
 collapse;table-layout:fixed;width:562pt'>
              <col width=64 span=2 style='width:48pt'>
              <col width=135 style='mso-width-source:userset;mso-width-alt:4807;width:101pt'>
              <col width=133 style='mso-width-source:userset;mso-width-alt:4721;width:100pt'>
              <col width=80 style='mso-width-source:userset;mso-width-alt:2844;width:60pt'>
              <col width=118 style='mso-width-source:userset;mso-width-alt:4209;width:89pt'>
              <col width=86 style='mso-width-source:userset;mso-width-alt:3043;width:64pt'>
              <col width=69 style='mso-width-source:userset;mso-width-alt:2446;width:52pt'>
              <tr height=42 style='mso-height-source:userset;height:31.8pt'>
                <td height=42 class=xl6714346 width=64 style='height:31.8pt;width:48pt;
  font-size:11.0pt;color:white;font-weight:700;text-decoration:none;text-underline-style:
  none;text-line-through:none;font-family:Calibri;border-top:1.0pt solid black;
  border-right:none;border-bottom:1.0pt solid black;border-left:none;
  background:#4F81BD;mso-pattern:#4F81BD none'>Frame Size</td>
                <td class=xl6714346 width=64 style='width:48pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>KW</td>
                <td class=xl6714346 width=135 style='width:101pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Max Output Current (AMPS)</td>
                <td class=xl6714346 width=133 style='width:100pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Continuous Output (AMPS)</td>
                <td class=xl6714346 width=80 style='width:60pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Frame</td>
                <td class=xl6714346 width=118 style='width:89pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Motor Weight (lbs.)</td>
                <td class=xl6714346 width=86 style='width:64pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Panel Weight (lbs.)</td>
                <td class=xl6714346 width=69 style='width:52pt;font-size:11.0pt;color:white;
  font-weight:700;text-decoration:none;text-underline-style:none;text-line-through:
  none;font-family:Calibri;border-top:1.0pt solid black;border-right:none;
  border-bottom:1.0pt solid black;border-left:none;background:#4F81BD;
  mso-pattern:#4F81BD none'>Price</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>5 HP</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>3.7</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>30</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>15</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>184 T</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>124</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>7</td>
                <td class=xl6814346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>$399.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt'>7.5 HP</td>
                <td class=xl6614346>5.5</td>
                <td class=xl6614346>28</td>
                <td class=xl6614346>19.5</td>
                <td class=xl6614346>213 T</td>
                <td class=xl6614346>166</td>
                <td class=xl6614346>10</td>
                <td class=xl6814346>$721.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>10 HP</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>7.4</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>39.5</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>28</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>215 T</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>199</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>12</td>
                <td class=xl6814346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>$799.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt'>15 HP</td>
                <td class=xl6614346>11.3</td>
                <td class=xl6614346>50</td>
                <td class=xl6614346>37</td>
                <td class=xl6614346>254 T</td>
                <td class=xl6614346>320</td>
                <td class=xl6614346>20</td>
                <td class=xl6814346>$949.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>20 HP</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>14.9</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>64</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>44</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>256 T</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>330</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>20</td>
                <td class=xl6814346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>$1,099.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt'>25 HP</td>
                <td class=xl6614346>18.5</td>
                <td class=xl6614346>80</td>
                <td class=xl6614346>52</td>
                <td class=xl6614346>284 T</td>
                <td class=xl6614346>376</td>
                <td class=xl6614346>30</td>
                <td class=xl6814346>$1,299.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;background:#D9D9D9;mso-pattern:
  #D9D9D9 none'>30 HP</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>22</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>64</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>97</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>324 T</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>470</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>45</td>
                <td class=xl6814346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;background:#D9D9D9;mso-pattern:#D9D9D9 none'>$1,589.00</td>
              </tr>
              <tr height=19 style='height:14.4pt'>
                <td height=19 class=xl6514346 style='height:14.4pt;font-size:11.0pt;
  color:black;font-weight:700;text-decoration:none;text-underline-style:none;
  text-line-through:none;font-family:Calibri;border-top:none;border-right:none;
  border-bottom:1.0pt solid black;border-left:none'>40 HP</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>29.6</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>87</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>120</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>364 T</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>600</td>
                <td class=xl6614346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>58</td>
                <td class=xl6814346 style='font-size:11.0pt;color:black;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri;border-top:none;border-right:none;border-bottom:1.0pt solid black;
  border-left:none'>$1,789.00</td>
              </tr>
              <![if supportMisalignedColumns]>
              <tr height=0 style='display:none'>
                <td width=64 style='width:48pt'></td>
                <td width=64 style='width:48pt'></td>
                <td width=135 style='width:101pt'></td>
                <td width=133 style='width:100pt'></td>
                <td width=80 style='width:60pt'></td>
                <td width=118 style='width:89pt'></td>
                <td width=86 style='width:64pt'></td>
                <td width=69 style='width:52pt'></td>
              </tr>
              <![endif]>
            </table>
            <p>&nbsp;</p>
          </div>
          <!----------------------------->
          <!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
        <!-----------------------------></td>
	</tr>
	<tr>
		<td colspan="5">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="5"><table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
		  <tr>
		    <td height="37" class="headers">Easy Installation</td>
	      </tr>
	    </table></td>
	</tr>
	<tr>
		<td height="61" colspan="5"><table width="938" border="0" align="center" cellpadding="0" cellspacing="0">
<tr>
			    <td width="17" height="51" bgcolor="#E9E9E9">&nbsp;</td>
			    <td valign="middle" bgcolor="#E9E9E9" class="content">Installation must be performed by a licensed electrician. All electrical codes must be followed. Any questions pertaining to installation should be directed to our technical support staff. CAUTION: Make sure main power is shut off before installing unit.</td>
			    <td width="17" bgcolor="#E9E9E9">&nbsp;</td>
	      </tr>
		  </table></td>
	</tr>
	<tr>
		<td colspan="2">&nbsp;</td>
		<td>
			<img src="images/specs&diagrams_14.png" width="560" height="553" alt="Installation Diagram"></td>
		<td colspan="2">&nbsp;</td>
	</tr>
	<tr>
		<td>
			<img src="images/spacer.gif" width="101" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="121" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="560" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="94" height="1" alt=""></td>
		<td>
			<img src="images/spacer.gif" width="101" height="1" alt=""></td>
	</tr>
</table>
<?php include("startingload.php"); ?>
<?php include("footer.php"); ?>
<!-- End Save for Web Slices -->
<script type="text/javascript" src="http://rotomastersllc.com/clickheat/js/clickheat.js"></script><noscript><p><a href="http://www.labsmedia.com/index.html">Open source tools</a></p></noscript><script type="text/javascript"><!--
clickHeatSite = 'Rotomasters';clickHeatGroup = 'specs';clickHeatServer = 'http://rotomastersllc.com/clickheat/click.php';initClickHeat(); //-->
</script>
</body>
</html>